### ISSUE TITLE
Upgrade to upstream v4.3?

### ISSUE THREAD

**Issue by BjornTwachtmann** [iuscommunity-pkg/php71u-pecl-redis#1]
Any chance of getting an upgrade of this package to the latest upstream into the repo? This version seems to be a fair bit behind https://github.com/phpredis/phpredis/releases

**Comment by carlwgeorge** [comment]
Same answer as https://github.com/iuscommunity-pkg/php72u-pecl-redis/issues/1.  Due to breaking upstream changes, we plan to keep php71u-pecl-redis and php72u-pecl-redis on 3.x.x, while php73-pecl-redis is on 4.x.x.
